#!/bin/bash

# Function to initialize account attributes
initialize_account() {
    accno=0
    name=""
    address=""
    amount=0.0
}

# Function to check if the account slot is available
check_availability() {
    if [[ $accno -eq 0 && -z $name && -z $address && -z $actype && $amount -eq 0.0 ]]; then
        return 0
    else
        return 1
    fi
}

# Function to create a new account
create_account() {
    echo "Your account number: "
    account_number=$((RANDOM + 1000000000))
    echo "Your account is being created..."

    sleep 2

    echo "Congratulations, $name! Your bank account has been created."
    echo "Account Number: $account_number"

    echo "Enter your full name: "
    read name

    echo "Enter your address: "
    read address

    echo "Enter how much money you want to deposit: "
    read amount

    echo "Account created successfully."
}# Function to deposit money into an account
deposit() {
    echo "Enter amount to deposit: "
    read d
    amount=$(echo "$amount + $d" | bc)
    echo "Updated. New amount: $amount"
}

# Function to withdraw money from an account
withdraw() {
    echo "Enter amount to withdraw: "
    read wd
    if [[ $(echo "$wd <= $amount" | bc) -eq 1 ]]; then
        amount=$(echo "$amount - $wd" | bc)
        echo "Amount withdrawn. Remaining amount: $amount"
    else
        echo "You don't have enough money in the account."
    fi
}

# Function to display account details
check_account() {
    echo "Name: $name"
    echo "Address: $address"
    echo "Amount: $amount"
}