#!/bin/bash

# Function to initialize account attributes
initialize_account() {
    local accno=0
    local name=""
    local address=""
    local amount=0.0
    local month=1
    local username=""
    local password=""
    local feedback=1
}

# Function to check if the account slot is available
check_availability() {
    if [[ $accno -eq 0 && -z $name && -z $address && -z $month && $amount -eq 0.0 ]]; then
        return 0
    else
        return 1
    fi
}

create_account() {
    echo "Enter your full name: "
    read name
    echo "You entered: $name"
    
    echo "Enter your address: "
    read address
    echo "You entered: $address"
    
    echo "Enter how much money you want to deposit: "
    read amount
    echo "You entered: $amount"
    
    echo "For how many month do you want to save your money: (write the number of months do you want)"
    read month
    
    # Generate a unique account number
    account_number=$((RANDOM + 1000000000))
    echo "Your account is being created..."
    sleep 1

    echo "Congratulations, $name! Your bank account has been created."
    echo "Account Number: $account_number"
    sleep 1
    
    echo "Enter your username: "
    read username
    sleep 1
    
    echo "Enter your password: "
    read password 
    sleep 1
   
    echo "$username,$password" >> user_credentials.txt
    sleep 1
    
    # Force output to appear immediately
    echo  "\n Account created successfully."
}

# Function to deposit money into an account
deposit() {
    echo "Enter amount to deposit: "
    read d
    amount=$(echo "$amount + $d" | bc)
    echo "Updated. New amount: $amount"
    sleep 4
}